[package]
name = "learning"
version = "0.1.0"
edition = "2021"

[dependencies]
cranelift-codegen = "0.110.2"
cranelift-module = "0.110.2"
cranelift-object = "0.110.2"
cranelift-frontend = "0.110.2"
target-lexicon = "0.12.16"
cranelift-native = "0.110.2"
